# Generated by Django 3.0.5 on 2020-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=40)),
                ('email', models.CharField(default='N/A', max_length=40)),
                ('phone', models.CharField(default='N/A', max_length=13)),
                ('desc', models.TextField()),
            ],
        ),
    ]
