# Generated by Django 3.0.5 on 2020-05-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(default='N/A', max_length=40)),
                ('email', models.CharField(default='N/A', max_length=40)),
                ('author', models.CharField(default='N/A', max_length=40)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
